config/routes.rb
Demo::Application.routes.draw do
  resources :alunos

  root 'alunos#index'

  

end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
    
  validates :nome, :presence => true
  validates :idade, :presence => true
  
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  def index
    @alunos = Aluno.all
  end

  def show
  end

  def new
    @aluno = Aluno.new
  end

  def edit
  end

  def create
    @aluno = Aluno.new(aluno_params)

    if @aluno.save
      redirect_to @aluno, notice: 'Aluno criado com sucesso.'
    else
      render action: 'new'
    end
  end

  def update
    if @aluno.update(aluno_params)
      redirect_to @aluno, notice: 'Aluno atualizado com sucesso.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @aluno.destroy
    redirect_to alunos_url
  end

  private
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    def aluno_params
      params.require(:aluno).permit(:nome, :idade)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alunos/_form.html.erb
<%= form_for(@aluno) do |f| %>
  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% @aluno.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :idade %><br>
    <%= f.number_field :idade %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar", class: 'button' %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Edição aluno</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @aluno %> | <%= link_to 'Voltar', alunos_path %>

app/views/alunos/index.html.erb
<h1>Listagem de Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.idade %></td>
        <td><%= link_to 'Exibir', aluno %></td>
        <td><%= link_to 'Editar', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Deletar', aluno, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Aluno', new_aluno_path, class: 'button' %>

app/views/alunos/new.html.erb
<h1>Novo aluno</h1>

<%= render 'form' %>

<%= link_to 'Voltar', alunos_path %>

app/views/alunos/show.html.erb
<h1>Exibindo Aluno</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @aluno.idade %>
</p>

<%= link_to 'Editar', edit_aluno_path(@aluno) %> |
<%= link_to 'Voltar', alunos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row">
    <div class="large-12 columns">
      <nav class="top-bar">
        <ul class="title-area">
          <li class="name">
            <h1><a href="#">Especialização em Desenvolvimento Web - Instituto Federal Catarinense - Mauricio Natanael Ferreira</a></h1>
          </li>          
        </ul>
      </nav>      
    </div>
  </div>
    
  <div class="row">
    <div class="large-12 columns">
      <hr />
      <%= yield %>
    </div>    
  </div>
</body>
</html>